version: "3.9"

networks:
  jenkins-nt:
    name: jenkins

volumes:
  jenkins-docker-certs:
  jenkins-data:

services:
  jenkins:
    image: "jenkins/jenkins"
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    networks:
      - jenkins-nt
    volumes: 
      - type: volume
        source: jenkins-docker-certs
        target: /certs/client
      - type: volume
        source: jenkins-data
        target: /var/jenkins_home
      
  docker:
    image: "docker:dind"
    privileged: true
    ports:
      - "2376:2376"
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    networks:
      - jenkins-nt
    volumes: 
      - type: volume
        source: jenkins-docker-certs
        target: /certs/client:ro
      - type: volume
        source: jenkins-data
        target: /var/jenkins_home
